### ISSUE TITLE
api.query.staking.currentElected() is not a function

### ISSUE THREAD

**Issue by mariopino** [polkadot-js/api#2040]
The query `api.query.staking.currentElected()` doesn't work in v1.6.1:

```
 TypeError: api.query.staking.currentElected is not a function
```

Is this a bug or has been replaced by any other?

Thank you!

**Comment by jacogr** [comment]
THe API decorates what is exposed by metadata. This is a not an API bug if no available. It means that chain runtime does not expose it. I would assume that is a new runtime though with the new staking interfaces - https://polkadot.js.org/api/substrate/storage.html#staking

**Comment by mariopino** [comment]
Thanks for pointing us in the right direction @jacogr!
