### ISSUE TITLE
api.derive.democracy.referendumVotes is not a function

### ISSUE THREAD

**Issue by vikiival** [polkadot-js/api#2085]
Hello,

I face a problem with fetching votes for selected referendum from api.
According to [implementation](https://github.com/polkadot-js/apps/blob/2d80f58a7dc972191d79d2d4afcea522e9557e84/packages/page-democracy/src/Overview/useVotes.ts#L98) I need to just call `api.derive.democracy.referendumVotes(index)`
unfortunately this method doesn't work on `api@1.8.1`

If I want to use old approach with `api.derive.democracy.referendumVotesFor(index)`
I got another error:
```
DRR: TypeError: "api.query.democracy.votersFor is not a function"
```
Used chain: `Kusama CC3`

Thanks 🚀

**Comment by jacogr** [comment]
If you want to use the derives for this, you are better suited with the 1.9-beta versions which has full support for the new democracy in all derives.

**Comment by jacogr** [comment]
PS: The apps UI always use the API betas, so it will be different from the release versions. These derives (new in 1.9) will change again significantly during the 1.9-beta series before release, so the beta interfaces are not "final" or anywhere close to it.

**Comment by vikiival** [comment]
@jacogr So what's the smartest approach to solve this using stable api ?

**Comment by jacogr** [comment]
Make the queries directly via `api.query.*` as per the chain you are connecting to. Each chain exposes the info and exposes queries via metadata, albeit in different places, there is no real magic behind derives.

All derives do is to grab info from multiple sources, supporting all available query types and construct it into a usable format - these undocumented for a reason, since they can change at will, and certainly after massive breaking democracy changes, they are changing very rapidly for the sake of efficiency.
