### ISSUE TITLE
Generated query interfaces do not import Option polkadot type

### ISSUE THREAD

**Issue by savudani8** [polkadot-js/api#3976]
When updating to v6.0.4 from v5.3.2, I'm getting compilation errors in `augment-api-query.ts` such as
```
src/interfaces/augment-api-query.ts:615:92 - error TS2749: 'Option' refers to a value, but is being used as a type here. Did you mean 'typeof Option'?

615       vaults: AugmentedQuery<ApiType, (arg: AccountId | string | Uint8Array) => Observable<Option<DefaultVault>>, [AccountId]> & QueryableStorageEntry<ApiType, [AccountId]>;
                                                                                               ~~~~~~

src/interfaces/augment-api-query.ts:615:92 - error TS4033: Property 'vaultRegistry' of exported interface has or is using private name 'Option'.

615       vaults: AugmentedQuery<ApiType, (arg: AccountId | string | Uint8Array) => Observable<Option<DefaultVault>>, [AccountId]> & QueryableStorageEntry<ApiType, [AccountId]>;
```
I can see that the `Option` type is not imported by the auto-generated code in `augment-api-query.ts`. These errors do not occur in `augment-api-rpc.ts`, where the `Option` type *is* imported from `@polkadot/types`

**Comment by jacogr** [comment]
It is a rough upgrade this one for me :)

**Comment by jacogr** [comment]
It _should_ be fixed in 6.0.5 which is current building on CI and should be available in 10-odd minutes. 

Please test once available. If it is still problematic (let's hope not), please send me a link to the repo so I can step through bit by bit.

**Comment by savudani8** [comment]
That fixed it, thanks! I upgraded in the hope that `.at(blockhash)` queries would be fixed, but it seems like they're still returning `undefined`. I checked the docs and the syntax hasn't changed. The query that doesn't work uses a custom struct type: https://github.com/interlay/interbtc-api/blob/master/src/parachain/oracle.ts#L122

**Comment by jacogr** [comment]
Would need to replicate - please do the following -

- log a separate issue for it (it is different to this one)
- Try the api.at(hash) form 
- Let me know which testnet on the apps UI I can replicate this on (via JS console)
