### ISSUE TITLE
Typegen fails because of WeightV2

### ISSUE THREAD

**Issue by crystalin** [polkadot-js/api#5288]
I've been trying to generate our new api-augment with polkadotjs `9.5.2` and I'm getting this error:
```
src/moonriver/interfaces/augment-api-tx.ts:1089:38 - error TS2344: Type 'FrameSupportWeightsWeightV2Weight' does not satisfy the constraint 'INumber'.

1089         [H256, Compact<u32>, Compact<FrameSupportWeightsWeightV2Weight>, Compact<u32>]
```

To reproduce:
```
git clone https://github.com/purestake/moonbeam
cd moonbeam
git checkout typescript-api-1900
cd typescript-api
npm ci
npm run build
```

**Comment by jacogr** [comment]
A struct cannot be a compact on the JS side. So for the specific tx the `#compact` annotation cannot work on this side. (The WeightV2 structure already had `#compact` on the fields)

**Comment by crystalin** [comment]
Thank you for the explanation.
I realize I forgot to re-generate the augment api before trying to build :/

**Comment by crystalin** [comment]
@jacogr , I have some additional issues.
After upgrade to 9.5.2 and generating (successfully) the types, using those types fail because of WeightV2, even if we are not using WeightV2 yet:

Ex:
```
smoke-tests/test-block-weight-per-class.ts:63:17 - error TS2740: Type 'SpWeightsWeightV2Weight' is missing the following properties from type 'BN': clone, toNumber, toArrayLike, toBuffer, and 81 more.

63                 normal,
                   ~~~~~~

```

How can prevent that ? Should we revert @polkadot/api to a prior version (I thought the types used where taken from the node metadata (we are using substrate 0.9.28)
