### ISSUE TITLE
Error TS2439 when building after upgrade of @polkadot/typegen from 6.1.1 to 6.11.1

### ISSUE THREAD

**Issue by gdethier** [polkadot-js/api#4309]
After upgrading all dependencies of our project, including `@polkadot/typegen` (from 6.1.1 to 6.11.1) and `@polkadot/api` (from 6.1.2 to 6.11.1) and generating types as described [here](https://polkadot.js.org/docs/api/examples/promise/typegen/), some of the generated files do not compile.

See below for an example of error message.

```
Failed to compile.

/home/gerard/workspaces/logion/logion-wallet/src/logion-chain/interfaces/augment-api-tx.ts
TypeScript error in /home/gerard/workspaces/logion/logion-wallet/src/logion-chain/interfaces/augment-api-tx.ts(5,3):
Import or export declaration in an ambient module declaration cannot reference module through relative module name.  TS2439

    3 | 
    4 | declare module '@polkadot/api/types/submittable' {
  > 5 |   import type { File, LocId, LocLink, LocType, MetadataItem, PeerId } from '../interfaces/default';
      |   ^
    6 |   import type { ApiTypes, AugmentedSubmittable, SubmittableExtrinsic, SubmittableExtrinsicFunction, SubmittableModuleExtrinsics } from '@polkadot/api/types';
    7 |   import type { Bytes, Compact, Option, U8aFixed, Vec, bool, u16, u32, u64, u8 } from '@polkadot/types';
    8 |   import type { TAssetBalance } from '@polkadot/types/interfaces/assets';
```

In our case, the impacted files are `augment-api-events.ts`, `augment-api-query.ts`, `augment-api-tx.ts` and `augment-types.ts`.

The workaround is to manually move the import statements before the `declared module ...` block. After that, the files compile and the application works as expected.

**Comment by jacogr** [comment]
Umpf. Thanks for reporting, can see why it didn't pop up in the API itself since all imports there are absolute.

So 2 options -

- split the local imports from the others and move them outside the templates
- convert the relative imports to absolute/package imports before using
