### ISSUE TITLE
Typegen generates invalid code after upgrading from 9.2 to 10.1

### ISSUE THREAD

**Issue by Nutomic** [polkadot-js/api#5582]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

We recently [upgraded](https://github.com/webb-tools/protocol-substrate/pull/308) @polkadot/typegen and related dependencies from 9.2.4 to 10.1.4. Since then typegen is not working anymore, and after a lot of investigation we still havent been able to find the cause nor any solution.
  
Here is an excerpt of the errors, see [this gist](https://gist.github.com/Nutomic/04ab6a29c5b4ba40aa225a93eaf8a0c0) for full log:
```
src/interfaces/augment-api-consts.ts:324:23 - error TS2304: Cannot find name 'SpWeightsWeightV2Weight'.

324       minerMaxWeight: SpWeightsWeightV2Weight & AugmentedConst<ApiType>;
~~~~~~~~~~~~~~~~~~~~~~~

src/interfaces/augment-api-consts.ts:324:23 - error TS4033: Property 'electionProviderMultiPhase' of exported interface has or is using private name 'SpWeightsWeightV2Weight'.

324       minerMaxWeight: SpWeightsWeightV2Weight & AugmentedConst<ApiType>;
~~~~~~~~~~~~~~~~~~~~~~~

src/interfaces/augment-api-consts.ts:369:24 - error TS2304: Cannot find name 'SpWeightsWeightV2Weight'.

369       signedMaxWeight: SpWeightsWeightV2Weight & AugmentedConst<ApiType>;
~~~~~~~~~~~~~~~~~~~~~~~

src/interfaces/augment-api-consts.ts:369:24 - error TS4033: Property 'electionProviderMultiPhase' of exported interface has or is using private name 'SpWeightsWeightV2Weight'.

369       signedMaxWeight: SpWeightsWeightV2Weight & AugmentedConst<ApiType>;
~~~~~~~~~~~~~~~~~~~~~~~

src/interfaces/augment-api-consts.ts:513:17 - error TS2304: Cannot find name 'FrameSupportPalletId'.

513       palletId: FrameSupportPalletId & AugmentedConst<ApiType>;
```

* **Steps to reproduce**
  - `git clone https://github.com/webb-tools/protocol-substrate.git`
  - Follow [readme instructions for installation](https://github.com/webb-tools/protocol-substrate#installation-)
  - `cargo build --release`
  - `./scripts/run-standalone.sh`
  - In another terminal, enter `types` subfolder and execute the yarn commands from [readme](https://github.com/webb-tools/protocol-substrate/tree/main/types#protocol-substrate-types)

I hope you can give us some hint how to solve this problem.

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [x] Node.js v16.19.1
    - [ ] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [x] TypeScript (tsc --version 5.0.2)
    - [ ] Other

**Comment by jacogr** [comment]
You first need to generate the types, then re-run with the augmentations.

The issue in the second is that an `import *` is used, and it ends up in a catch-22 when they types are not there yet. (It is not due to API upgrade, rather chain upgrade with new types - this is a long-standing issue that affects _some_ upgrades. Not horrible enough to spend time re-writing the import interfaces)

Additionally, there are some changes in how-to-run, there is an issue open on that with a lot of pointers for the 9 -> 10 upgrade a couple below this one.
