### ISSUE TITLE
Tsc build failed with typescript 4.5.2

### ISSUE THREAD

**Issue by jiqiang90** [polkadot-js/api#4227]
And this is the error I have got 

```
node_modules/@polkadot/types/create/registry.d.ts:8:22 - error TS2589: Type instantiation is excessively deep and possibly infinite.

 export declare class TypeRegistry implements Registry {
                       ~~~~~~~~~~~~

Found 1 error.


```

**Comment by jacogr** [comment]
I saw they had some changes for "deep types" in the upcoming list, but it is was supposed to make it better, not worse :)

**Comment by jacogr** [comment]
Was able to remove some (nicely readable) calls and flatten them in #4232, where the build/linting used to fail with 4.5.2 it now passed. (And importantly also still works on 4.4.4 and eralier)
