### ISSUE TITLE
Typescript compile errors after upgrade from v9.14 to v10.x 

### ISSUE THREAD

**Issue by TheGoldenEye** [polkadot-js/api#5612]
After switching to version 10.x of the polkadot api I got compile errors from tsc like this:

```
$ tsc
node_modules/@polkadot/util-crypto/keccak/asU8a.d.ts:1:23 - error TS1452: 'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.

1 /// <reference types="node" resolution-mode="require"/>
                        ~~~~

node_modules/@polkadot/util-crypto/pbkdf2/encode.d.ts:1:23 - error TS1452: 'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.

1 /// <reference types="node" resolution-mode="require"/>
                        ~~~~
```
typescript version: 4.9.5

My project: https://github.com/TheGoldenEye/polka-store/tree/development

**Comment by jacogr** [comment]
This should be logged in the common repo since that is where it originates, it is not really the API.

There is nothing that can be done here from this side. The TS compiler adds these to the output as soon as you start using `node16` or `nodenext` resolution - which is what the libs use.

The only real solution, according to google, is to add the [skipLibCkeck](https://www.typescriptlang.org/tsconfig#skipLibCheck) option to your config.

**Comment by TheGoldenEye** [comment]
thanks for tip, problem solved
